variables:
  WINDOWS_CMAKE_IMAGE: cunity/windows-1803-cmake:latest


stages:
  - build
  - test
  - release

.cunit-build-template: &cunit-build
  script:
    - git clean -f -d -x
    - mkdir cmake-build
    - cd cmake-build
    - cmake ..
    - cmake --build . -- -j4
    - ctest --output-on-failure
    - ./CUnit/cunit_test
    - ./Examples/AutomatedTest/t-automated
    - junit2html --summary-matrix TestAutomated-Results.xml
    - pushd Examples/CI
    - ./cicd-pass-plain
    - ./cicd-pass-setupfuncs
    - junit2html --summary-matrix *-Results.xml
    - popd
    - cpack -G TGZ CUnit
  artifacts:
    paths:
    - CUnit/CUnit/CUnitCI.h
    - cmake-build/cunit-*.tar.gz
    - cmake-build/cunit-*.deb
    - cmake-build/Examples/CI/*-Results.*
    reports:
      junit: cmake-build/Examples/CI/*-Results.xml

cunit-ubuntu-18.04:
  <<: *cunit-build
  stage: build
  image: registry.gitlab.com/cunity/linux-cmake-builders/ubuntu-18.04:master


cmake-direxample-ubuntu-18.04:
  stage: test
  image: registry.gitlab.com/cunity/linux-cmake-builders/ubuntu-18.04:master
  script:
  - cd CMakeExamples/CMakeSubmodule
  - ln -s ../../. cunit-x.y.z
  - mkdir bld
  - cd bld
  - cmake ..
  - cmake --build .
  - ./test-program
  dependencies:
  - cunit-ubuntu-18.04


cmake-pkgexample-ubuntu-18.04:
  stage: test
  image: registry.gitlab.com/cunity/linux-cmake-builders/ubuntu-18.04:master
  script:
    - find . -type f -name "*.tar.gz"
    - mkdir -p packages/cunit
    - tar -vxf cmake-build/cunit-3.0.*.tar.gz --strip-components=1 -C packages/cunit
    - cd CMakeExamples/CMakeFindPackage
    - mkdir bld
    - cd bld
    - cmake .. -DCUnit_DIR=$(pwd)/../../../packages/cunit/CUnit/share/cmake
    - cmake --build .
    - ./test-program
  dependencies:
    - cunit-ubuntu-18.04

cunit-ubuntu-17.10: 
  <<: *cunit-build
  stage: build
  image: registry.gitlab.com/cunity/linux-cmake-builders/ubuntu-17.10:master

cunit-win1803-vs2015:
  stage: build
  image: cunity/windows-1803-cmake:latest
  tags:
    - cunity-windows-1803-docker
  script:
    - mkdir bld
    - cd bld
    - cmake -G "Visual Studio 14 2015 Win64" .. || exit /b
    - cmake --build . --config Release || exit /b
    - ctest -C Release || exit \b
  artifacts:
    paths:
      - bld/Examples/CI/*-Results.*

cunit-solaris-amd64:
  stage: build
  tags:
    - solaris-11-amd64
  script:
    - mkdir bld
    - cd bld
    - cmake ..
    - cmake --build .

pages:
  image: registry.gitlab.com/cunity/doxygen-image/ubuntu-18.04-doxygen:master
  stage: release
  dependencies:
  - cunit-ubuntu-18.04
  script:
  - doxygen Doxyfile
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  - feature-cunit-ci
